export const SET_LENGTH = 'SET_LENGTH';
export const SET_WIDTH = 'SET_WIDTH';
export const SET_BORDER_TYPE = 'SET_BORDER_TYPE';

export const SET_EDIT_DIMENSIONS_MODE = 'SET_EDIT_DIMENSIONS_MODE';
export const SET_EDIT_BORDER_MODE = 'SET_EDIT_BORDER_MODE';

export const SHOW_CENTER_MATERIAL_MODE = 'SHOW_CENTER_MATERIAL_MODE';
export const SHOW_CENTER_MATERIAL_FIRST_CHILDREN_MODE = 'SHOW_CENTER_MATERIAL_FIRST_CHILDREN_MODE';
export const SHOW_CENTER_MATERIAL_SECOND_CHILDREN_MODE = 'SHOW_CENTER_MATERIAL_SECOND_CHILDREN_MODE';

export const SHOW_INNER_BORDER_MATERIAL_MODE = 'SHOW_INNER_BORDER_MATERIAL_MODE';
export const SHOW_INNER_BORDER_MATERIAL_FIRST_CHILDREN_MODE = 'SHOW_INNER_BORDER_MATERIAL_FIRST_CHILDREN_MODE';
export const SHOW_INNER_BORDER_MATERIAL_SECOND_CHILDREN_MODE = 'SHOW_INNER_BORDER_MATERIAL_SECOND_CHILDREN_MODE';

export const SHOW_OUTER_BORDER_MATERIAL_MODE = 'SHOW_OUTER_BORDER_MATERIAL_MODE';
export const SHOW_OUTER_BORDER_MATERIAL_FIRST_CHILDREN_MODE = 'SHOW_OUTER_BORDER_MATERIAL_FIRST_CHILDREN_MODE';
export const SHOW_OUTER_BORDER_MATERIAL_SECOND_CHILDREN_MODE = 'SHOW_OUTER_BORDER_MATERIAL_SECOND_CHILDREN_MODE';

export const SHOW_PIPING_MATERIAL_MODE = 'SHOW_PIPING_MATERIAL_MODE';

export const SET_CENTER_MATERIAL_TYPE = 'SET_CENTER_MATERIAL_TYPE';
export const SET_INNER_BORDER_MATERIAL_TYPE = 'SET_INNER_BORDER_MATERIAL_TYPE';
export const SET_OUTER_BORDER_MATERIAL_TYPE = 'SET_OUTER_BORDER_MATERIAL_TYPE';
export const SET_PIPING_MATERIAL_TYPE = 'SET_PIPING_MATERIAL_TYPE';

export const SET_CURRENT_MATERIAL_HOVER = 'SET_CURRENT_MATERIAL_HOVER';
export const SET_CURRENT_MATERIAL_HOVER_COORDS = 'SET_CURRENT_MATERIAL_HOVER_COORDS';

export const SET_RUG_CURRENT_VIEW = 'SET_RUG_CURRENT_VIEW';
export const SET_RUG_POSITION = 'SET_RUG_POSITION';
export const SET_RUG_POSITION_GUEST = 'SET_RUG_POSITION_GUEST';

export const  ZOOM_RUG_IN = 'ZOOM_RUG_IN';
export const  ZOOM_RUG_OUT = 'ZOOM_RUG_OUT';

export const SHOW_RUG_CORNER = 'SHOW_RUG_CORNER';
export const SHOW_ROOM_PRESETS = 'SHOW_ROOM_PRESETS';

export const LOAD_CENTER_MATERIALS_SUCCESS = 'LOAD_CENTER_MATERIALS_SUCCESS';
export const LOAD_CENTER_MATERIALS_FIRST_CHILDREN_SUCCESS = 'LOAD_CENTER_MATERIALS_FIRST_CHILDREN_SUCCESS';
export const LOAD_CENTER_MATERIALS_SECOND_CHILDREN_SUCCESS = 'LOAD_CENTER_MATERIALS_SECOND_CHILDREN_SUCCESS';

export const LOAD_OUTER_BORDER_MATERIALS_SUCCESS = 'LOAD_OUTER_BORDER_MATERIALS_SUCCESS';
export const LOAD_OUTER_BORDER_MATERIALS_FIRST_CHILDREN_SUCCESS = 'LOAD_OUTER_BORDER_MATERIALS_FIRST_CHILDREN_SUCCESS';
export const LOAD_OUTER_BORDER_MATERIALS_SECOND_CHILDREN_SUCCESS = 'LOAD_OUTER_BORDER_MATERIALS_SECOND_CHILDREN_SUCCESS';

export const LOAD_INNER_BORDER_MATERIALS_SUCCESS = 'LOAD_INNER_BORDER_MATERIALS_SUCCESS';
export const LOAD_INNER_BORDER_MATERIALS_FIRST_CHILDREN_SUCCESS = 'LOAD_INNER_BORDER_MATERIALS_FIRST_CHILDREN_SUCCESS';
export const LOAD_INNER_BORDER_MATERIALS_SECOND_CHILDREN_SUCCESS = 'LOAD_INNER_BORDER_MATERIALS_SECOND_CHILDREN_SUCCESS';

export const LOAD_PIPING_MATERIALS_SUCCESS = 'LOAD_PIPING_MATERIALS_SUCCESS';

export const RUG_PRICE_CALCULATED = 'RUG_PRICE_CALCULATED';

export const SHOW_LOGIN_REGISTER_MODAL = 'SHOW_LOGIN_REGISTER_MODAL';

export const SHOW_LOGIN_MODAL = 'SHOW_LOGIN_MODAL';
export const SHOW_REGISTER_MODAL = 'SHOW_REGISTER_MODAL';
export const SHOW_GUEST_MODAL = 'SHOW_GUEST_MODAL';

export const CLEAR_CENTER_MATERIAL_FIRST_CHILDREN = 'CLEAR_CENTER_MATERIAL_FIRST_CHILDREN';
export const CLEAR_CENTER_MATERIAL_SECOND_CHILDREN = 'CLEAR_CENTER_MATERIAL_SECOND_CHILDREN';
export const CLEAR_INNER_BORDER_MATERIAL_FIRST_CHILDREN = 'CLEAR_INNER_BORDER_MATERIAL_FIRST_CHILDREN';
export const CLEAR_INNER_BORDER_MATERIAL_SECOND_CHILDREN = 'CLEAR_INNER_BORDER_MATERIAL_SECOND_CHILDREN';
export const CLEAR_OUTER_BORDER_MATERIAL_FIRST_CHILDREN = 'CLEAR_INNER_BORDER_MATERIAL_FIRST_CHILDREN';
export const CLEAR_OUTER_BORDER_MATERIAL_SECOND_CHILDREN = 'CLEAR_INNER_BORDER_MATERIAL_SECOND_CHILDREN';

export const SET_GUEST_USER = 'SET_GUEST_USER';



