export const SET_LENGTH = 'SET_LENGTH';
export const SET_WIDTH = 'SET_WIDTH';
export const SET_BORDER_TYPE = 'SET_BORDER_TYPE';
export const SET_EDIT_DIMENSIONS_BORDER_MODE = 'SET_EDIT_DIMENSIONS_BORDER_MODE';